"""add sync_source to meetings

Revision ID: 13997c20c3c6
Revises: a9bf8a019ab4
Create Date: 2026-02-23 17:12:33.366281
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '13997c20c3c6'
down_revision: Union[str, None] = 'a9bf8a019ab4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('meetings', sa.Column('sync_source', sa.String(length=16), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('meetings', 'sync_source')
    # ### end Alembic commands ###
